# Generated by Django 4.1.3 on 2022-12-19 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_rename_desc_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='description',
        ),
    ]
